### PR TITLE
Nones

### PR DESCRIPTION
**Pull request by jdhenshaw**
changes of interest include the following commits:

c610889
d9f9fa3

I'm closing PR #30 and including all changes here instead. 

@GiantMolecularCloud can you try this on your machine and make sure the behaviour outlined in issue #34 is fixed? I have also converted the scouse errors to 0.0 but need to check this doesn't break things further down the line in stage 3.

### CODE REVIEW

**Comment by GiantMolecularCloud** [comment]
Unfortunately, this does not fix the problem. I still get the same error message.

**Comment by jdhenshaw** [comment]
Could you try updating your pyspeckit and let me know if that helps?

**Comment by GiantMolecularCloud** [comment]
Any particular branch? I have 0.1.22.dev0 installed which is what I get from `pip install https://github.com/pyspeckit/pyspeckit/archive/master.zip`
The documentation is titled v0.1.22.dev2847 but `pyspeckit.__version__` always lists v0. How do I get the newer version?

**Comment by jdhenshaw** [comment]
Yes, get the latest from github (I'm on 0.1.22.dev2847 right now).

**Comment by GiantMolecularCloud** [comment]
Master seems to be the newest branch but cloning that results in `pyspeckit.__version__ == 0.1.22.dev0`

**Comment by jdhenshaw** [comment]
can you try uninstall your current version first and then install using python setup.py install?

**Comment by GiantMolecularCloud** [comment]
Uninstalling did not help but another way of forcing pip to load the github version worked: `pip install git+https://github.com/pyspeckit/pyspeckit@master`
Will test the new pyspeckit version and report back.

**Pull request merged**
